WEEKLY_CAPACITY = 30
LEVEL_HOURS = {"XS": 1, "S": 2, "M": 4, "L": 8, "XL": 16}
USE_MOCK_DATA = False
USE_MOCK_CUSTOMISATIONS = False
USE_MOCK_BANKING = False
USE_MOCK_EMAIL = False
USE_MOCK_SERVICENOW = False
USE_MOCK_PROJECTS = False
